// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDC8Gnj6LAoYqNlgFfUe9Cs-jFgwja0rAY',
    appId: '1:386113379551:web:6bd17e1c219f76252f5d6a',
    messagingSenderId: '386113379551',
    projectId: 'food-delivery-5ccf6',
    authDomain: 'food-delivery-5ccf6.firebaseapp.com',
    storageBucket: 'food-delivery-5ccf6.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB4dx-pxLS8uYja7UG-GfBAVAUgq9rdBY8',
    appId: '1:386113379551:android:5de50f5cca859d8b2f5d6a',
    messagingSenderId: '386113379551',
    projectId: 'food-delivery-5ccf6',
    storageBucket: 'food-delivery-5ccf6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBY0Lh5bRGs4vOulq6T5SQ4F1BoirDSexI',
    appId: '1:386113379551:ios:878c5cd3e8bc58482f5d6a',
    messagingSenderId: '386113379551',
    projectId: 'food-delivery-5ccf6',
    storageBucket: 'food-delivery-5ccf6.appspot.com',
    iosClientId: '386113379551-1ipl3s6v4u7o92mandq2nteojh2nl8q5.apps.googleusercontent.com',
    iosBundleId: 'com.example.foodDelivery',
  );
}
